### ISSUE TITLE
Adding BME280 sensor Data

### ISSUE THREAD

**Issue by OhioJoe** [jeffmer/tinyPulsePPG#2]
I am using a 128x64 ssd1306. I can write data to oled display's lower half. I would like to have the PulseOxy data display on the first 31 lines and the BME sensor data display on lines 33-63. 
I can add 'test' data ie: temp = 98.6 but cannot figure out how to add live data.
I added a function to calculate the variables, but calling the function hangs the program.  

> void draw_oled(int msg) {
>   oled.firstPage();
> 
>   do {
>     switch (msg) {
>       case 0:  oled.drawStr(10, 0, F("Device error"), 1);
>         break;
>       case 1:
>         oled.drawStr(13, 2, F("PLACE"), 1); //13,10
>         oled.drawStr(10, 16, F("FINGER"), 1); //10,20
>         oled.drawChar(100, 0, voltage / 10 + '0');
>         oled.drawChar(106, 0, '.');
>         oled.drawChar(112, 0, voltage % 10 + '0');
>         oled.drawChar(118, 0, 'V');
>         oled.drawStr(84, 16, F("Display"), 1); //84,14
>         oled.drawStr(0, 34, F("T: "), 1);
>         oled.drawChar(26, 34,  'F');
> //        temp = 1.8 * bme280.readTemperature() + 32;
>         temp = 98.6;
>         //        Serial.println(temp);
>         print_digit(12, 34, temp, "F", 2, 1);
>         oled.drawStr(64, 34, F("H: "), 1);
>         print_digit(76, 34, humi, "F", 2, 1);
>         oled.drawChar(94, 34,  '%');
>         oled.drawStr(0, 45, F("Alt: "), 1);
> 
>         print_digit(25, 45, alt, "F", 3, 1);
>         oled.drawStr(0, 57, F("P: "), 1);
>         print_digit(12, 57, pres, "F", 3, 1);
>         oled.drawStr(34, 57, F("mmHg"), 1);
>         if (draw_Red)
>           oled.drawStr(84, 24, F("Red"), 1);
>         else
>           oled.drawStr(84, 24, F("IR"), 1);
>         if (filter_for_graph)
>           oled.drawStr(108, 24, F("Avg"), 1);
>         else
>           oled.drawStr(108, 24, F("Raw"), 1);
>         break;

**Comment by jeffmer** [comment]
I would suggest you make temp a global variable and call your function in the main program loop. The problem is that to avoid having a large buffer the draw routines are called multiple times. I suspect you are hanging due to an i2c conflict.
