### ISSUE TITLE
Image example usage

### ISSUE THREAD

**Issue by Arritmic** [jeffmer/tinyPulsePPG#7]
Hi @jeffmer ,

Could I use one of the images of the device prototype in my thesis?
If yes, how should I reference you??

Best,
Arritmic

**Comment by jeffmer** [comment]
Yes of course, feel free to use it. Simply reference the github repository would be fine. 

BTW: what is your thesis about?

**Comment by Arritmic** [comment]
It is about remote photoplethysmography and remote ballistography using cameras and radars. It includes from development of novel algorithms, to use cases and implementation in embedded devices.

**Comment by jeffmer** [comment]
That sounds like a lot of fun. I am a retired computing science academic - would love to see your thesis when you finish it - I am sure you will put a PDF on line.

**Comment by Arritmic** [comment]
Yes, sure!! It will be an honor. Please, find my humble contribution in google scholar: https://scholar.google.fi/citations?user=vLYIwqUAAAAJ&hl=en
